volumes:
  grafana-data:
  db_data:

services:
  prometheus:
    image: prom/prometheus:v2.37.9
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - ./prometheus/config.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./data:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  app:
    build: ./nestjs-app
    container_name: nestjs-app
    command: npm run start:prod
    ports:
      - 3010:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: development_pass
      POSTGRES_DB: test-api
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
